1. Basics

In [3]:
import numpy as np
import sys

In [1]:
#python list
list = [1,2,3]
list

[1, 2, 3]

In [4]:
#numpy array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
#both data type are mutable
list[0] = 0
list

[0, 2, 3]

In [6]:
a[2] = 0
a


array([1, 2, 0])

In [11]:
#both can be indexed and can be used for slicing operations
list[2]


3

In [9]:
a[2]

0

In [12]:
list[:2]

[0, 2]

In [13]:
a[1:]

array([2, 0])

In [14]:
#a list cannot directly handle a mathematical operations,while array can.


In [15]:
list = [0,1,2,3,4,5]

In [16]:
list*2

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [17]:
a = np.array([0,1,2,3,4,5])

In [20]:
a*2
#or
s = np.multiply(list,2)
s

array([ 0,  2,  4,  6,  8, 10])

In [21]:
#array consumes less memory than a list

In [22]:
list

[0, 1, 2, 3, 4, 5]

In [23]:
sys.getsizeof(list)

104

In [24]:
a

array([0, 1, 2, 3, 4, 5])

In [25]:
a.itemsize

8

In [26]:
#that is 8 bytes and 104 bytes memory for one element in a list and in an array

Some basics just to practice:

In [29]:
b = np.array([[1,2,3,4,4],[3,4,5,5,6]])
b

array([[1, 2, 3, 4, 4],
       [3, 4, 5, 5, 6]])

In [30]:
#get dimension
b.ndim

2

In [31]:
#get shape
b.shape

(2, 5)

In [33]:
#get type
b.dtype

dtype('int64')

In [37]:
b.nbytes

80

2. Array creation

In [38]:
# convert python sequence to numpy arrays

In [39]:
list = [1,2,3,4,5]#list
arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

In [41]:
tuple = (0,2,3,4,5)#tuple
arr = np.array(tuple)
arr

array([0, 2, 3, 4, 5])

In [42]:
rng = range(5)
arr = np.array(rng)
print(arr)

[0 1 2 3 4]


In [43]:
#Intrinsic NumPy array creation functions

In [15]:
arr = np.arange(1,5) #creating 1d array using arange()
print(arr)
x = np.arange(start = 1, stop = 10, step= 2)
print(x)

[1 2 3 4]
[1 3 5 7 9]


In [45]:
arr = np.linspace(0,1,5)#creating 1d array using linspace()
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
arr = np.logspace(0,1,3)#create 1d with logspace()
print(arr)

[ 1.          3.16227766 10.        ]


In [17]:
arr = np.random.random(5)#creates the 1d array of random values with random()
print(arr)

[0.41581093 0.14338813 0.19695268 0.62165961 0.19983609]


In [18]:
arr = np.eye(3, dtype =int) #creates 2d array
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [54]:
arr = np.zeros((4,3)) #creates 2d array
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
a = np.zeros(4, dtype = int)
b = np.zeros([4, 3], dtype = float)
c = np.zeros((4, 3, 2), float, 'C')
print("the values of array a : \n", a)
print("the values of array b : \n", b)
print("the values of array c : \n", c)

the values of array a : 
 [0 0 0 0]
the values of array b : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
the values of array c : 
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [22]:
arr = np.ones((4,3)) #creates 2d array
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. Replicating, joining, or mutating existing arrays

In [25]:
#replicating
arr = np.array([1,2,3,4,5])

repeat = np.repeat(arr,2)#repeats we also can use tile()
print(repeat)

[1 1 2 2 3 3 4 4 5 5]


In [28]:
#concatenate
arr1 = np.array([0, 2, 3])
arr2 = np.array([1, 5, 6])

new_arr = np.concatenate((arr1 ,arr2))
print(new_arr)


[0 2 3 1 5 6]


In [30]:
#stack vertically, horizontally
new_arr = np.vstack((arr1,arr2))
print(new_arr)

[[0 2 3]
 [1 5 6]]


In [29]:
new_arr = np.hstack((arr1,arr2))
print(new_arr)

[0 2 3 1 5 6]


In [31]:
#mutate 
new_arr = np.array([1,2,3,4,5])
print(new_arr)
#reverse
new_arr1 = np.flip(new_arr)
print(new_arr1)
#sort
new_arr2 = np.sort(new_arr1)
print(new_arr2)

[1 2 3 4 5]
[5 4 3 2 1]
[1 2 3 4 5]


3. Creating arrays from raw bytes using strings or buffers

In [66]:
#creating arrays from raw bytes using string

strbyte = b'\x01\x02\x03\x04\x05\x06\x07\x08'
arr_from_str = np.frombuffer(strbyte, dtype=np.uint8)
print(arr_from_str)

[1 2 3 4 5 6 7 8]


In [67]:
#creating arrays from raw bytes using buffers
buffbyte = bytearray(b'\x01\x02\x03\x04\x05\x06\x07\x08')

arr_from_buffer = np.frombuffer(buffbyte, dtype=np.uint8)
print(arr_from_buffer)

[1 2 3 4 5 6 7 8]


5. Use of special library functions (e.g., random)

In [68]:
random_num = np.random.random()
print(random_num)

0.4852518535373851


In [69]:
random_int = np.random.randint(1, 10)
print(random_int)

7


In [70]:
random_array = np.random.rand(5)
print(random_array)

[0.33723937 0.03243761 0.08281447 0.96653783 0.10672072]


In [71]:
random_int_array = np.random.randint(1, 10, (3, 3))#create 3*3 random int array between 1 adn 10
print(random_int_array)

[[4 2 6]
 [9 9 7]
 [9 6 8]]


In [73]:
#np.random.choice() can also be used

5. Data types

In [74]:
arr = np.array([True, False, True], dtype=np.bool_)
print(arr.dtype)

bool


In [ ]:
#similarly others

In [1]:
#Numpy performance vs python list

In [2]:
#memory consumption numpy array vs python list

In [4]:
import numpy as np
import sys



eg_list = [1, 2, 3, 4, 5]
eg_array = np.array([1, 2, 3, 4, 5])


In [5]:
# memory usage of Python list
print(sys.getsizeof(eg_list))

# memory usage of numpy array
print(eg_array.nbytes)

104
40


In [11]:
import time


my_list = list(range(10000))
my_array = np.arange(10000)

# element wise multiplication using python list
start_time = time.time()
result_list = [x * 2 for x in my_list]
end_time = time.time()
execution_time_list = end_time - start_time
print("execution time for python list is:", execution_time_list)

#element wise multiplication using numpy array
start_time = time.time()
result_array = my_array * 2
end_time = time.time()
execution_time_array = end_time - start_time
print("execution time for numpy array is:", execution_time_array)

if execution_time_list < execution_time_array:
    print("python list operation is faster")
else:
    print("numpy array operation is faster")


execution time for python list is: 0.0008635520935058594
execution time for numpy array is: 0.0003993511199951172
numpy array operation is faster


In [24]:
# creating a two dimensional array
twoD_array = np.array([[1, 2, 3], [4, 5, 6]])

# accessing elements in a two dimensional array
print(twoD_array[0, 1]) 

# creating a three dimensional array
threeD_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# accessing elements in a three dimensional array
print(threeD_array[0, 1, 1])  


2
4
